### ISSUE TITLE
Unable to install reportwriter3043.mxt

### ISSUE THREAD

**Issue by RockyRoads2591** [mrbray99/Moneydance#15]
Downloaded the mxt from https://bitbucket.org/mikerb/moneydance-2019/downloads/.  When installing into Moneydance 2022 (4040) get an error:

There was an error loading the extension file...
Unable to load extension with ID'reportwriter3043' due to missing metadata.

**Comment by mrbray99** [comment]
A couple of things:
1. You need to rename the file to reportwriter.mxt before you load it into MD.
2. Why did you choose github to raise the issue? Please use the MD support site https://infinitekind.tenderapp.com/discussions.
Thanks
Mike Bray
